version: '3.7'
services:
  elixir-spec.dev:
    image: "elixir:1.16-alpine"
    volumes:
      - ./elixir_spec:/usr/src
    working_dir: /usr/src
    command: sh serve.sh
    environment:
      - MIX_ENV=dev

  # usado para las pruebas de integracion
  crystal-spec.dev:
    image: crystallang/crystal:1.10-alpine
    links:
      - "elixir-spec.dev:elixir-spec.dev"
    volumes:
      - .:/usr/src
    working_dir: /usr/src
    depends_on:
      - elixir-spec.dev
